[keyboard]
bindings = [
  # Clipboard
  { key = "V", mods = "Super", action = "Paste" },
  { key = "S", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Super", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "V", mods = "Control", action = "Paste" },
  { key = "Insert", mods = "Shift", action = "Paste" },

  # Scrolling
  { key = "Up", mods = "Control|Shift", action = "ScrollLineUp" },
  { key = "Down", mods = "Control|Shift", action = "ScrollLineDown" },
  
  # Miscellaneous
  { key = "Up", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Down", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "Backspace", mods = "Control|Shift", action = "ResetFontSize" },
]
